
[General]
	#How long to wait (in seconds) before seeding new growths if no existing spread is detected
	#Range: > 1
	seedTime = 60
	#When dragonskin blocks decay, they decay in patches of connected blocks, rather than individual blocks
	patchyDecay = true
	#Start the world in heal mode. Perhaps you want to configure your pack to start the plague when a certain event happens. (The command /healplague off can start it.)
	healDefault = false
	#The speed at which dragonskin grows. 100 is roughly the speed of spreading grass
	#Range: > 0
	growthPercent = 100
	#Display debugging data in the console
	debug = false
	#The speed at which dragonskin decays in heal mode. 100 is roughtly the speed that grass dies when covered. If decaying too much at once lags, try lowering this.
	#Range: 0 ~ 100
	decayPercent = 10
	#How quickly a decaying dragonscale block should turn into an ore. 100 means 'the moment it lands'. Technically this is the chance it has to change each time the block ticks.
	#Range: 0 ~ 100
	orePercent = 90
	#This causes plague block spread to be batched and performed at once, with an interval of this many seconds. The overall growth rate should be roughly the same, but it might help with lag.
	#Range: > 0
	spreadDelay = 60
	#How often (percentage) a decaying skin block should drop a piece of dragonsscale (as opposed to just disappearing). Too high might lag the server.
	#Range: 0 ~ 100
	sloughPercent = 10
	#Maximum distance from a player to seed growths
	#Range: > 1
	seedRadius = 128
	#The maximum number of block spreads performed in a single update. This limits the total spread to an average of spreadCap per spreadDelay seconds. Lower this if you're getting a lot of lag/dropped ticks on spreading. (0=No limit)
	#Range: > 0
	spreadCap = 500
	#The blocks that might be released from Dragonscale. This can be a resource ID (minecraft:stone) or a tagentry (forge:ores/iron)
	dropBlocks = ["appliedenergistics2:quartz_block", "ars_nouveau:mana_gem_block", "biggerreactors:graphite_block", "botania:elementium_block", "botania:manasteel_block", "botania:terrasteel_block", "create:zinc_block", "immersiveengineering:storage_uranium", "mekanism:block_fluorite", "mekanism:block_osmium", "minecraft:coal_block", "minecraft:diamond_block", "minecraft:emerald_block", "minecraft:gold_block", "minecraft:iron_block", "minecraft:lapis_block", "minecraft:netherite_block", "minecraft:quartz_block", "minecraft:redstone_block", "miniutilities:ender_pearl_block", "projectred-exploration:peridot_block", "projectred-exploration:ruby_block", "projectred-exploration:sapphire_block", "soulbound:ancientmetal_block", "tconstruct:cobalt_block", "thermal:apatite_block", "thermal:cinnabar_block", "thermal:coal_coke_block", "thermal:copper_block", "thermal:enderium_block", "thermal:lead_block", "thermal:nickel_block", "thermal:niter_block", "thermal:signalum_block", "thermal:silver_block", "thermal:sulfur_block", "thermal:tin_block", "tropicraft:azurite_block", "tropicraft:eudialyte_block", "tropicraft:zircon_block"]
	#How many chunks to seed when seeding new growths
	#Range: > 1
	seedChunks = 50

