
[options]
	#Message that displays when Teleport is blocked
	blockedmessage = "The veil between worlds is too heavy to pass"
	#Prevents Death by Teleporting Player to Spawn if trying to enter an Ender Portal
	preventdeath = true
	#Description for the Advancements
	description = "Obtain an %item%"
	#Comma seperated list of Dimension Resource Names
	dimresname = "minecraft:the_end"
	#Title for the Advancements
	craftedmessage = "Pierce the veil"
	#Comma seperated list of items that when crafted unlock the corresponding dimension
	craftitems = "contenttweaker:end_orb"
	#Comma seperated list of Dimension Display Names
	dimnames = "End"

